export type McpDocsSection = {
  id: string;
  title: string;
  description: string;
  workflow: string[];
  tools: string[];
};

export type McpToolDoc = {
  name: string;
  purpose: string;
  writes: boolean;
  input: string;
  example: Record<string, unknown>;
  returns: string;
  dashboardImpact: string;
  safety: string;
};

export type McpToolGroup = {
  id: string;
  title: string;
  purpose: string;
  startupCheck: string;
  tools: McpToolDoc[];
};

export const mcpDocsSections: McpDocsSection[] = [
  {
    id: "setup",
    title: "Setup",
    description: "Create a token, add the hosted endpoint to the agent, then read the account snapshot before calling tools.",
    workflow: ["Create a token from Hosted MCP Access.", "Paste the generated config into the MCP client.", "Ask the agent to read the account snapshot before any write."],
    tools: ["resources/read", "tools/list", "tools/call"],
  },
  {
    id: "snapshot",
    title: "Account Snapshot",
    description: "Confirms which CRM user, role, organization, counts, upcoming events, and recent activity the agent is operating on.",
    workflow: ["Read the snapshot at startup.", "Confirm email and role with the user.", "Use returned counts and IDs as context for later work."],
    tools: ["account snapshot resource"],
  },
  {
    id: "mail",
    title: "Mail",
    description: "Manage connected inboxes, read messages, draft replies, send approved email, and perform mailbox actions.",
    workflow: ["List connected accounts.", "Search or read messages.", "Draft first, send only after approval."],
    tools: ["mail.list_accounts", "mail.search_messages", "mail.read_message", "mail.draft_reply", "mail.send_email", "mail.batch_action"],
  },
  {
    id: "leads",
    title: "Leads",
    description: "List, create, update, upload, score, log interactions, and convert user-owned leads.",
    workflow: ["List or upload leads.", "Open a lead before updating it.", "Log every important call, note, or reply."],
    tools: ["leads.list", "leads.get", "leads.create", "leads.update", "leads.upload_csv", "leads.score", "leads.log_interaction", "leads.convert_to_customer"],
  },
  {
    id: "outreach",
    title: "Outreach",
    description: "Preview campaigns, launch approved outreach, send follow-ups, process replies, and inspect campaign analytics.",
    workflow: ["Preview recipients and sender accounts.", "Get explicit approval.", "Launch with confirm true and process replies later."],
    tools: ["outreach.preview_campaign", "outreach.launch_campaign", "outreach.list_campaigns", "outreach.get_campaign", "outreach.send_follow_up", "outreach.process_replies"],
  },
  {
    id: "forms",
    title: "Forms",
    description: "Create forms, generate share messages, inspect submissions, and sync intake data into CRM records.",
    workflow: ["Create the form and fields.", "Share the public form link.", "Review submissions and meeting intake data."],
    tools: ["forms.list", "forms.create", "forms.delete", "forms.get_submissions", "forms.submit_public", "forms.generate_share_message"],
  },
  {
    id: "calendar",
    title: "Calendar",
    description: "Manage availability, check free slots, create events, book client meetings, and cancel events safely.",
    workflow: ["Read settings.", "Check availability before booking.", "Use confirm true only after approval for client meetings."],
    tools: ["calendar.get_settings", "calendar.update_settings", "calendar.list_events", "calendar.check_availability", "calendar.create_event", "calendar.book_client_meeting", "calendar.cancel_event"],
  },
  {
    id: "billing",
    title: "Billing",
    description: "Manage BritLedger clients, invoices, quotations, payments, balances, and invoice email sending.",
    workflow: ["List or create a client.", "Create invoice or quote with line items.", "Use returned balance due and record payments later."],
    tools: ["billing.list_clients", "billing.create_client", "billing.list_invoices", "billing.create_invoice", "billing.update_invoice", "billing.record_payment", "billing.create_quotation", "billing.list_quotations", "billing.convert_quote_to_invoice", "billing.send_invoice"],
  },
  {
    id: "admin",
    title: "Admin",
    description: "Manage pricing plans, discount events, trials, users, system email profiles, and operations snapshots. Admin tools fail unless the token belongs to an ADMIN user.",
    workflow: ["Preview admin changes with confirm false.", "Apply only after approval.", "Audit operations and activity after changes."],
    tools: ["admin.pricing.list_plans", "admin.pricing.upsert_plan", "admin.pricing.upsert_discount_event", "admin.users.search", "admin.users.update", "admin.system_email.update_profile", "admin.operations.snapshot"],
  },
];

export const mcpSetupSteps = [
  "Open /settings/mcp inside BritCRM.",
  "Create a token for the agent. Copy it immediately; it is shown once.",
  "Paste the hosted config into the MCP client.",
  "Connect the client, call tools/list, then read the account snapshot resource.",
  "Confirm the account email and role before any write action.",
];

export const mcpSafetyRules = [
  "Read before writing. Always list/get/preview existing records before create, update, send, delete, or convert.",
  "Treat mail sends, outreach launches, meeting bookings, billing sends, admin updates, and deletions as real production actions.",
  "Use confirm=false first whenever a tool supports confirmation. Use confirm=true only after user approval.",
  "Never invent IDs. Pull IDs from list/get results.",
  "Never expose passwords, tokens, reset tokens, SMTP secrets, or database values.",
  "All normal tools are scoped to the token owner. Admin tools require an ADMIN token and must still follow preview-first behavior.",
];

export const mcpResponseContract = {
  success: true,
  data: {},
  error: null,
};

export const mcpErrorContract = {
  success: false,
  data: null,
  error: "Human readable error message",
};

export const mcpToolGroups: McpToolGroup[] = [
  {
    id: "mail-tools",
    title: "Unified Inbox And Mail",
    purpose: "Read connected inboxes, draft replies, send approved direct emails, and apply mailbox actions.",
    startupCheck: "Call mail.list_accounts first. Use the returned accountId for all mailbox operations.",
    tools: [
      {
        name: "mail.list_accounts",
        purpose: "Find active SMTP/IMAP accounts connected to the current CRM user.",
        writes: false,
        input: "No input.",
        example: {},
        returns: "User identity and active email account metadata. Passwords are never returned.",
        dashboardImpact: "Uses accounts managed in Settings > Email.",
        safety: "If no accounts are returned, do not try to send or read mail.",
      },
      {
        name: "mail.search_messages",
        purpose: "List recent messages from one mailbox.",
        writes: false,
        input: "accountId?, mailbox='INBOX', query?, limit=50.",
        example: { accountId: "email_account_id", mailbox: "INBOX", limit: 10 },
        returns: "Message IDs, sender, subject, snippet, date, read/star status.",
        dashboardImpact: "Reads the connected unified inbox.",
        safety: "Use returned message id as uid for read, draft, or batch actions.",
      },
      {
        name: "mail.read_message",
        purpose: "Read one message body.",
        writes: false,
        input: "uid, accountId?, mailbox='INBOX'.",
        example: { accountId: "email_account_id", mailbox: "INBOX", uid: "35" },
        returns: "Full email body, HTML/text, sender, recipient, subject, date.",
        dashboardImpact: "Reads one inbox message.",
        safety: "Do not quote private email content unless the user asks.",
      },
      {
        name: "mail.draft_reply",
        purpose: "Prepare a reply without sending it.",
        writes: false,
        input: "uid, instructions, accountId?, mailbox='INBOX', tone='professional'.",
        example: { uid: "35", instructions: "Politely say we will review and reply soon.", tone: "professional" },
        returns: "Recipient, reply subject, HTML body, sent=false.",
        dashboardImpact: "No dashboard write. It is a generated draft payload only.",
        safety: "Show the draft to the user before sending.",
      },
      {
        name: "mail.send_email",
        purpose: "Send a real direct email through a connected mailbox.",
        writes: true,
        input: "to, subject, htmlBody, accountId?, senderName?, replyToUid?. The to field is a single email string.",
        example: { to: "client@example.com", subject: "Follow up", htmlBody: "<p>Hello, following up.</p>", accountId: "email_account_id" },
        returns: "Account ID, recipient, subject, replyToUid, messageId when SMTP returns it.",
        dashboardImpact: "Sends email and increments sentToday for the mailbox.",
        safety: "Use only after explicit user approval. For multiple recipients, call once per recipient or use outreach.",
      },
      {
        name: "mail.batch_action",
        purpose: "Mark, archive, trash, spam, star, or unstar mailbox messages.",
        writes: true,
        input: "accountId?, mailbox='INBOX', uids[], action. Actions: archive, trash, spam, read, unread, star, unstar.",
        example: { accountId: "email_account_id", mailbox: "INBOX", uids: ["35"], action: "read" },
        returns: "Success and failed counts.",
        dashboardImpact: "Changes message state in the connected mailbox.",
        safety: "Avoid trash/spam/archive unless the user explicitly approved the selected messages.",
      },
    ],
  },
  {
    id: "lead-tools",
    title: "Leads",
    purpose: "Create, import, inspect, score, update, log, and convert CRM leads.",
    startupCheck: "Call leads.list before updates. Use leads.get for full context before changing an existing lead.",
    tools: [
      {
        name: "leads.list",
        purpose: "Search and paginate user-owned leads.",
        writes: false,
        input: "query?, status?, categoryId?, limit=50, offset=0, sortBy='updatedAt', sortDirection='desc'.",
        example: { query: "acme", limit: 10 },
        returns: "Total, paging values, and lead rows.",
        dashboardImpact: "Reads Leads page data.",
        safety: "Use this to find IDs instead of guessing.",
      },
      {
        name: "leads.get",
        purpose: "Read one lead with related CRM activity.",
        writes: false,
        input: "leadId.",
        example: { leadId: "lead_id" },
        returns: "Lead details, interactions, tasks, deals, and campaign history where available.",
        dashboardImpact: "Reads one Leads page record.",
        safety: "Call before updating important fields.",
      },
      {
        name: "leads.create",
        purpose: "Create a new user-owned lead.",
        writes: true,
        input: "name, email, plus optional phone, company, licenseType, areaOfOperation, dealFocus, budgetRange, website, industry, location, address, rating, linkedin, source, status, categoryId.",
        example: { name: "Jane Client", email: "jane@example.com", company: "Example Ltd", source: "MCP" },
        returns: "Created lead and optional score output.",
        dashboardImpact: "New record appears on Leads.",
        safety: "Do not create duplicates; search by email first when possible.",
      },
      {
        name: "leads.update",
        purpose: "Update fields on one user-owned lead.",
        writes: true,
        input: "leadId plus editable lead fields.",
        example: { leadId: "lead_id", status: "Contacted", company: "Updated Company" },
        returns: "Updated lead.",
        dashboardImpact: "Lead page changes immediately.",
        safety: "Only send changed fields. Preserve existing data unless user requested overwrite.",
      },
      {
        name: "leads.upload_csv",
        purpose: "Import leads from CSV text.",
        writes: true,
        input: "csvText, categoryId?, source='MCP CSV Upload', updateExisting=false.",
        example: { csvText: "name,email,company\nJane,jane@example.com,Example Ltd", source: "MCP import" },
        returns: "Imported count, skipped count, imported lead IDs, skipped rows.",
        dashboardImpact: "Creates or optionally updates Leads page records.",
        safety: "Preview/inspect CSV columns before importing large batches.",
      },
      {
        name: "leads.score",
        purpose: "Run lead scoring and insights.",
        writes: true,
        input: "leadId.",
        example: { leadId: "lead_id" },
        returns: "Score and insights.",
        dashboardImpact: "May update AI score/insights on the lead.",
        safety: "Use after lead data is complete enough to score.",
      },
      {
        name: "leads.log_interaction",
        purpose: "Log a note, call, email, or other interaction on a lead.",
        writes: true,
        input: "leadId, type='Note', content, sentiment?, moveToContacted=true.",
        example: { leadId: "lead_id", type: "Call", content: "Client asked for pricing.", sentiment: "Positive" },
        returns: "Created interaction.",
        dashboardImpact: "Interaction appears in lead activity.",
        safety: "Keep notes factual and attributable.",
      },
      {
        name: "leads.convert_to_customer",
        purpose: "Convert a lead into a customer/contact record.",
        writes: true,
        input: "leadId, confirm=false.",
        example: { leadId: "lead_id", confirm: false },
        returns: "Preview when confirm=false; conversion result when confirm=true.",
        dashboardImpact: "Creates/updates customer and changes lead lifecycle.",
        safety: "Always preview first, then confirm only after user approval.",
      },
    ],
  },
  {
    id: "outreach-tools",
    title: "Outreach Campaigns",
    purpose: "Preview, launch, follow up, and inspect outreach campaigns.",
    startupCheck: "Call mail.list_accounts and outreach.preview_campaign before launching.",
    tools: [
      {
        name: "outreach.preview_campaign",
        purpose: "Validate recipients and sender accounts without sending email.",
        writes: false,
        input: "campaignName, senderName, subject, htmlContent, recipients, includeManualRecipients, leadFilters, smtpAccountIds[].",
        example: { campaignName: "August follow up", subject: "Checking in", htmlContent: "<p>Hello {{FirstName}}</p>", recipients: "client@example.com", includeManualRecipients: true },
        returns: "Recipient count, invalid recipients, duplicates, sender accounts, readyToLaunch.",
        dashboardImpact: "No write.",
        safety: "Show preview summary to the user before launch.",
      },
      {
        name: "outreach.launch_campaign",
        purpose: "Create and send an outreach campaign.",
        writes: true,
        input: "Same as preview plus confirm=false.",
        example: { campaignName: "August follow up", subject: "Checking in", htmlContent: "<p>Hello</p>", recipients: "client@example.com", confirm: true },
        returns: "Campaign ID, status, recipient count, source breakdown.",
        dashboardImpact: "Campaign appears on Campaigns and sends emails in background.",
        safety: "Use confirm=true only after preview and approval. Delivery may finish asynchronously.",
      },
      {
        name: "outreach.list_campaigns",
        purpose: "List campaign history and metrics.",
        writes: false,
        input: "status?, limit=50, offset=0.",
        example: { limit: 10 },
        returns: "Campaign rows with sender, counts, and metrics.",
        dashboardImpact: "Reads Campaigns page.",
        safety: "Use after launch to verify status changed from Active to Completed.",
      },
      {
        name: "outreach.get_campaign",
        purpose: "Read one campaign with lead-level status.",
        writes: false,
        input: "campaignId.",
        example: { campaignId: "campaign_id" },
        returns: "Campaign details, recipients, sent/open/reply counts.",
        dashboardImpact: "Reads campaign analytics.",
        safety: "Use to verify sentAt and bounced rows before reporting delivery.",
      },
      {
        name: "outreach.send_follow_up",
        purpose: "Create a follow-up campaign for prior campaign recipients.",
        writes: true,
        input: "campaignId, targetFilter, customStatus?, senderName, subject, htmlContent, smtpAccountIds[], confirm=false.",
        example: { campaignId: "campaign_id", targetFilter: "not_replied", subject: "Following up", htmlContent: "<p>Checking in</p>", confirm: false },
        returns: "Preview or launched follow-up result.",
        dashboardImpact: "Creates and sends follow-up campaign when confirmed.",
        safety: "Preview first to avoid over-emailing contacts.",
      },
      {
        name: "outreach.process_replies",
        purpose: "Scan inboxes and match replies to campaigns.",
        writes: true,
        input: "No input.",
        example: {},
        returns: "Scanned count, matched count, account summary, since timestamp.",
        dashboardImpact: "Updates campaign reply metrics and lead status where matched.",
        safety: "Safe to run periodically; it reads inboxes and updates matched statuses.",
      },
    ],
  },
  {
    id: "form-tools",
    title: "Forms",
    purpose: "Create client intake forms, share them, read submissions, and submit intake data.",
    startupCheck: "Call forms.list before creating duplicates. Use forms.get_submissions after sharing.",
    tools: [
      {
        name: "forms.list",
        purpose: "List user-owned forms.",
        writes: false,
        input: "search?, limit=50, offset=0.",
        example: { limit: 10 },
        returns: "Total, paging values, forms.",
        dashboardImpact: "Reads Forms page.",
        safety: "Use to avoid duplicate intake forms.",
      },
      {
        name: "forms.create",
        purpose: "Create a public form with fields and optional meeting scheduling.",
        writes: true,
        input: "title, description?, fields[], meetingSchedulingEnabled=false, meetingDurationMin=60. Field types: TEXT, TEXTAREA, DROPDOWN, RADIO, CHECKBOX, EMAIL, PHONE.",
        example: { title: "Client Intake", fields: [{ label: "Email", type: "EMAIL", required: true }] },
        returns: "Created form, fields, public URL.",
        dashboardImpact: "New form appears on Forms.",
        safety: "Ask user what data to collect before creating client-facing forms.",
      },
      {
        name: "forms.delete",
        purpose: "Delete a form and submissions.",
        writes: true,
        input: "formId, confirm=false.",
        example: { formId: "form_id", confirm: false },
        returns: "Preview or deletion result.",
        dashboardImpact: "Removes form/submissions when confirmed.",
        safety: "Never use confirm=true unless the user explicitly approves deletion.",
      },
      {
        name: "forms.get_submissions",
        purpose: "Read submissions for one form.",
        writes: false,
        input: "formId, limit=50, offset=0.",
        example: { formId: "form_id", limit: 20 },
        returns: "Form metadata and parsed submissions.",
        dashboardImpact: "Reads form submission data.",
        safety: "Treat submitted personal data as private.",
      },
      {
        name: "forms.submit_public",
        purpose: "Submit intake data into a form on behalf of a user/client.",
        writes: true,
        input: "formId, responses, optional meeting.",
        example: { formId: "form_id", responses: { field_id: "Jane Client" } },
        returns: "Submission and CRM sync result.",
        dashboardImpact: "Creates a form submission and may sync lead/customer data.",
        safety: "Use only when intentionally submitting real intake data.",
      },
      {
        name: "forms.generate_share_message",
        purpose: "Generate a message containing the public form link.",
        writes: false,
        input: "formId, tone='professional'.",
        example: { formId: "form_id", tone: "professional" },
        returns: "Public URL and share message.",
        dashboardImpact: "No write.",
        safety: "Send/share only after user approves the wording.",
      },
    ],
  },
  {
    id: "calendar-tools",
    title: "Calendar And Meetings",
    purpose: "Manage availability, check slots, create events, book client meetings, and cancel events.",
    startupCheck: "Call calendar.get_settings and calendar.check_availability before booking meetings.",
    tools: [
      {
        name: "calendar.get_settings",
        purpose: "Read availability settings.",
        writes: false,
        input: "No input.",
        example: {},
        returns: "availableStart, availableEnd, timeZone, reminder account.",
        dashboardImpact: "Reads Calendar settings.",
        safety: "Use timezone in returned settings when presenting slots.",
      },
      {
        name: "calendar.update_settings",
        purpose: "Update availability settings.",
        writes: true,
        input: "availableStart='09:00', availableEnd='17:00', timeZone='UTC', reminderAccountId?.",
        example: { availableStart: "09:00", availableEnd: "17:00", timeZone: "Europe/London" },
        returns: "Updated settings.",
        dashboardImpact: "Changes Calendar availability.",
        safety: "Confirm timezone and hours with the user first.",
      },
      {
        name: "calendar.list_events",
        purpose: "List events in a date range.",
        writes: false,
        input: "start?, end?, limit=200.",
        example: { start: "2026-08-24T00:00:00Z", end: "2026-08-31T00:00:00Z", limit: 50 },
        returns: "Calendar events.",
        dashboardImpact: "Reads Calendar page.",
        safety: "Use before booking if a precise range matters.",
      },
      {
        name: "calendar.check_availability",
        purpose: "Compute free slots for a date and duration.",
        writes: false,
        input: "date, durationMin=60.",
        example: { date: "2026-08-24", durationMin: 30 },
        returns: "Available slots.",
        dashboardImpact: "No write.",
        safety: "Offer only returned slots to avoid double-booking.",
      },
      {
        name: "calendar.create_event",
        purpose: "Create a manual calendar event after conflict checking.",
        writes: true,
        input: "title, description?, start, end, source='MCP'.",
        example: { title: "Client call", start: "2026-08-24T10:00:00Z", end: "2026-08-24T10:30:00Z" },
        returns: "Created event.",
        dashboardImpact: "Event appears on Calendar.",
        safety: "Use ISO datetimes and avoid vague local times.",
      },
      {
        name: "calendar.book_client_meeting",
        purpose: "Book a client meeting with room/calendar resources and optional confirmation emails.",
        writes: true,
        input: "title, clientEmail, start, end, notes?, sendConfirmation=true, confirm=false.",
        example: { title: "Onboarding", clientEmail: "client@example.com", start: "2026-08-24T10:00:00Z", end: "2026-08-24T10:30:00Z", confirm: false },
        returns: "Preview or created meeting/event result.",
        dashboardImpact: "Creates locked calendar event and meeting resources when confirmed.",
        safety: "Preview first, then confirm after user/client approval.",
      },
      {
        name: "calendar.cancel_event",
        purpose: "Cancel/delete a calendar event and linked meeting resources.",
        writes: true,
        input: "eventId, confirm=false.",
        example: { eventId: "event_id", confirm: false },
        returns: "Preview or cancellation result.",
        dashboardImpact: "Removes event when confirmed.",
        safety: "Never cancel with confirm=true without explicit approval.",
      },
    ],
  },
  {
    id: "billing-tools",
    title: "Billing And BritLedger",
    purpose: "Manage clients, invoices, quotations, payments, balances, and invoice sends through BritLedger.",
    startupCheck: "Call billing.list_clients first or create a client, then use returned clientId for invoices and quotes.",
    tools: [
      {
        name: "billing.list_clients",
        purpose: "Search BritLedger billing clients.",
        writes: false,
        input: "search?, page=1, pageSize=25, includeBalances=false.",
        example: { search: "Acme", page: 1, pageSize: 10, includeBalances: true },
        returns: "Clients, pagination, optional balances.",
        dashboardImpact: "Reads Billing clients.",
        safety: "Use returned IDs for invoices and quotes.",
      },
      {
        name: "billing.create_client",
        purpose: "Create a billing client.",
        writes: true,
        input: "name, email?, phone?, address?, companyName?, vatNumber?, isActive=true.",
        example: { name: "Acme Ltd", email: "billing@acme.example", companyName: "Acme Ltd" },
        returns: "Created client.",
        dashboardImpact: "New client appears in Billing.",
        safety: "Search existing clients before creating duplicates.",
      },
      {
        name: "billing.list_invoices",
        purpose: "List invoices and balances.",
        writes: false,
        input: "clientId?, status?, search?, page=1, pageSize=25.",
        example: { clientId: "client_id", page: 1, pageSize: 10 },
        returns: "Invoices with totals and balance due.",
        dashboardImpact: "Reads Billing invoices.",
        safety: "Use before updating or recording payments.",
      },
      {
        name: "billing.create_invoice",
        purpose: "Create an invoice with server-side calculations.",
        writes: true,
        input: "clientId, invoiceNumber?, issueDate?, dueDate?, currency='GBP', status='DRAFT', lineItems[], discount=0, advancePayment=0, markPaid=false, notes?. Line items accept description, quantity, unitCost/rate/amount, vatRate.",
        example: { clientId: "client_id", currency: "GBP", lineItems: [{ description: "Website design", quantity: 1, unitCost: 500, vatRate: 20 }], discount: 50, advancePayment: 100 },
        returns: "Invoice and calculations including subtotal, VAT, total, paid, balanceDue.",
        dashboardImpact: "Invoice appears in Billing.",
        safety: "Confirm line items, VAT, discount, advance payment, and balance before creating.",
      },
      {
        name: "billing.update_invoice",
        purpose: "Update an invoice and recalculate totals.",
        writes: true,
        input: "invoiceId plus optional invoice fields, lineItems[], discount, advancePayment, markPaid.",
        example: { invoiceId: "invoice_id", discount: 25 },
        returns: "Updated invoice and calculations.",
        dashboardImpact: "Changes invoice totals/status.",
        safety: "Read invoice first and change only requested fields.",
      },
      {
        name: "billing.record_payment",
        purpose: "Record a payment against an invoice.",
        writes: true,
        input: "invoiceId, amount, currency?, paymentMethod?, notes?.",
        example: { invoiceId: "invoice_id", amount: 100, currency: "GBP", paymentMethod: "Bank transfer" },
        returns: "Invoice, paidBefore, paidAfter, balanceDue.",
        dashboardImpact: "Reduces invoice balance due.",
        safety: "Confirm amount and currency before recording payment.",
      },
      {
        name: "billing.create_quotation",
        purpose: "Create a quotation with server-side calculations.",
        writes: true,
        input: "clientId, quotationNumber?, issueDate?, expiryDate?, currency='GBP', status='Draft', lineItems[], discount=0, notes?.",
        example: { clientId: "client_id", lineItems: [{ description: "Consulting", quantity: 2, unitCost: 150, vatRate: 20 }] },
        returns: "Quotation and calculations.",
        dashboardImpact: "Quotation appears in Billing.",
        safety: "Confirm terms before sending or converting.",
      },
      {
        name: "billing.list_quotations",
        purpose: "List quotations.",
        writes: false,
        input: "clientId?, status?, page=1, pageSize=25.",
        example: { page: 1, pageSize: 10 },
        returns: "Quotation rows and pagination.",
        dashboardImpact: "Reads Billing quotations.",
        safety: "Use returned quotationId for conversion.",
      },
      {
        name: "billing.convert_quote_to_invoice",
        purpose: "Convert quotation to invoice.",
        writes: true,
        input: "quotationId, confirm.",
        example: { quotationId: "quotation_id", confirm: false },
        returns: "Preview or created invoice.",
        dashboardImpact: "Creates invoice from quote when confirmed.",
        safety: "Requires confirm=true after user approval.",
      },
      {
        name: "billing.send_invoice",
        purpose: "Email an invoice through BritLedger.",
        writes: true,
        input: "invoiceId, toEmail, subject?, personalMessage?, includePaymentLink=true.",
        example: { invoiceId: "invoice_id", toEmail: "client@example.com", includePaymentLink: true },
        returns: "Send result from BritLedger.",
        dashboardImpact: "Sends invoice email.",
        safety: "Only send after final invoice review and approval.",
      },
    ],
  },
  {
    id: "admin-tools",
    title: "Admin, Pricing, And Operations",
    purpose: "Admin-only controls for pricing, discounts, trials, users, system email, and operations.",
    startupCheck: "Read the account snapshot and verify role is ADMIN before calling admin tools.",
    tools: [
      {
        name: "admin.pricing.list_plans",
        purpose: "Read pricing plans, discount events, and public pricing preview.",
        writes: false,
        input: "includePublicPreview=true.",
        example: { includePublicPreview: true },
        returns: "Plans, offers, public preview.",
        dashboardImpact: "Reads Admin pricing data.",
        safety: "Available only to ADMIN tokens.",
      },
      {
        name: "admin.pricing.upsert_plan",
        purpose: "Create or update a pricing plan.",
        writes: true,
        input: "id?, slug, name, description, monthlyPriceCents, seatLimit, features[], stripePriceId?, isActive, isPopular, sortOrder, trialDays, ctaLabel?, confirm=false.",
        example: { slug: "business", name: "Business", monthlyPriceCents: 4900, seatLimit: 10, features: ["CRM", "Outreach"], trialDays: 7, confirm: false },
        returns: "Preview or saved plan and public preview.",
        dashboardImpact: "Changes frontend pricing and admin plans when confirmed.",
        safety: "Always use confirm=false first.",
      },
      {
        name: "admin.pricing.upsert_discount_event",
        purpose: "Create or update frontend-visible discount events.",
        writes: true,
        input: "id?, title, description, discountPercent, couponCode?, startsAt, endsAt, appliesToPlanSlug?, isActive, confirm=false.",
        example: { title: "August offer", discountPercent: 20, startsAt: "2026-08-01T00:00:00Z", endsAt: "2026-09-01T00:00:00Z", confirm: false },
        returns: "Preview or saved offer and public preview.",
        dashboardImpact: "Changes pricing offers shown to users when confirmed.",
        safety: "Check dates and discount percent before confirm.",
      },
      {
        name: "admin.users.search",
        purpose: "Search users with organization summary.",
        writes: false,
        input: "query='', role?, status?, plan?, page=1, pageSize=25.",
        example: { query: "client@example.com", page: 1, pageSize: 10 },
        returns: "Users and organization summaries without secrets.",
        dashboardImpact: "Reads Admin users.",
        safety: "Do not expose sensitive user data beyond the admin task.",
      },
      {
        name: "admin.users.update",
        purpose: "Update user role/status and subscription fields.",
        writes: true,
        input: "userId, role?, status?, plan?, subscriptionStatus?, seatLimit?, confirm=false.",
        example: { userId: "user_id", plan: "business", subscriptionStatus: "active", confirm: false },
        returns: "Preview or updated user.",
        dashboardImpact: "Changes user/admin/subscription state.",
        safety: "Preview first. Self-demotion/self-suspension is blocked.",
      },
      {
        name: "admin.system_email.update_profile",
        purpose: "Update transactional or newsletter SMTP profile.",
        writes: true,
        input: "profile, host, port, username, password?, fromEmail, fromName, secureMode, isEnabled, confirm=false.",
        example: { profile: "transactional", host: "smtp.example.com", port: 587, username: "mailer", fromEmail: "hello@example.com", fromName: "BritCRM", secureMode: "STARTTLS", confirm: false },
        returns: "Redacted SMTP profile status.",
        dashboardImpact: "Changes system email sending profile.",
        safety: "Password is write-only. Never print or store SMTP password in prompts.",
      },
      {
        name: "admin.operations.snapshot",
        purpose: "Read operational counts and configuration health.",
        writes: false,
        input: "No input.",
        example: {},
        returns: "Counts, config readiness, redacted profiles, recent activity.",
        dashboardImpact: "Reads admin operational state.",
        safety: "Use for audits and health checks.",
      },
    ],
  },
];
